---

# Apparmor の変更は bind9 のためなので、bind9 の再起動よりも前に書くこと
- name: apparmor 再読み込み
  service: name=apparmor state=reloaded

- name: Samba bind9 再起動
  service: name=bind9 state=restarted

- name: Restart SAMBA AD DC
  service:
    name: samba-ad-dc
    state: restarted

...

