---

- name: Play for Samba 4
  hosts: main
  sudo: true
  tasks:
    - apt: update_cache=yes cache_valid_time=86400
    - apt:
        name: "{{item}}"
        state: present
        install_recommends: false
      with_items:
        - ntp
        - samba
    - service:
        name: smbd
        state: stopped
    - service:
        name: samba-ad-dc
        state: started
    - debug: var=ansible_eth1
    - stat: path=/var/lib/samba/private/tls
      register: stat_samba_tls
    - shell: rm -f /etc/samba/smb.conf && samba-tool domain provision --use-rfc2307 --option="interfaces=lo eth1" --option="bind interfaces only=yes" --option="dns forwarder=8.8.8.8" --use-ntvfs --realm=DOM.AYUTAYA.COM --domain=DOM --server-role=dc --dns-backend=SAMBA_INTERNAL --option="netbios name=HOGE"
      when: not stat_samba_tls.stat.exists
      notify: Restart SAMBA AD DC
  handlers:
    - name: Restart SAMBA AD DC
      service:
        name: samba-ad-dc
        state: restarted

...


    # - template:
    #     src: smb.conf.j2
    #     dest: /etc/samba/smb.conf
    #   notify: Restart SAMBA AD DC


    # - debug: var=ohai_network
    # samba-tool domain provision --use-rfc2307 --option="interfaces=lo eth0" --option="bind interfaces only=yes" --option="dns forwarder={{gateway}}" --use-ntvfs

    # samba-tool domain provision --use-rfc2307 --option="interfaces=lo eth1" --option="bind interfaces only=yes" --option="dns forwarder=10.0.2.3" --use-ntvfs --realm=DOM.AYUTAYA.COM --domain=DOM --server-role=dc --dns-backend=SAMBA_INTERNAL

