---

- name: Play for Samba 4
  hosts: main
  roles:
    - { role: common, sudo: true }
    - { role: namesvc, sudo: true }
    - { role: samba4, sudo: true }
    - { role: apache, sudo: true }

...

    # - template:
    #     src: smb.conf.j2
    #     dest: /etc/samba/smb.conf
    #   notify: Restart SAMBA AD DC


    # - debug: var=ohai_network
    # samba-tool domain provision --use-rfc2307 --option="interfaces=lo eth0" --option="bind interfaces only=yes" --option="dns forwarder={{gateway}}" --use-ntvfs

    # samba-tool domain provision --use-rfc2307 --option="interfaces=lo eth1" --option="bind interfaces only=yes" --option="dns forwarder=10.0.2.3" --use-ntvfs --realm=SAMDOM.EXAMPLE.COM --domain=DOM --server-role=dc --dns-backend=SAMBA_INTERNAL

