---

- name: Samba 4 testing environment
  hosts: main
  roles:
    - { role: common, sudo: true }
    - { role: namesvc, sudo: true }
    - { role: samba4, sudo: true }
    - { role: krbclient, sudo: true }
    - { role: apache, sudo: true }
    - { role: sites, sudo: true }
...
